proxy: initializing cSide...
clientSide: __init__ called
clientSide: socket created
clientSide: socket bound
clientSide: socket listening
proxy: cSide initialized
proxy: initializing sSide...
serverSide: __init__ called
serverSide: socket created
serverSide: socket bound
proxy: sSide initiaized
proxy: Ip address of the proxy is: ***.***.***.**
proxy: started cSide
clientSide: run called
clientSide: Waiting for client connection...
serverSide: run called
serverSide: waiting for client to get connection...  
command invoked: stop
proxy: Stopping...
clientSide: Stopping...
clientSide: Cannot close socket.
clientSide: Closed client connection.
serverSide: Stopping...
serverSide: Disconnected from server.
proxy: Joining cSide thread...
clientSide: Waiting for client connection...
clientSide: loop broken
cleanup: Exception in <clientSide(Thread-1, started 2684)>. Printing traceback:
NoneType: None

cleanup: Cleaning up after exception in <clientSide(Thread-1, started 2684)>.
proxy: Stopping...
clientSide: Stopping...
clientSide: Cannot close socket.
clientSide: Closed client connection.
serverSide: Stopping...
serverSide: Disconnected from server.
proxy: Joining cSide thread...
cleanup: Exception in <TCP.proxy object at 0x000002353C479348>. Printing traceback:
Traceback (most recent call last):
  File "C:\Users\aweso\Documents\Source\Python\proxy\TCP.py", line 90, in stop
    self.cSide.join()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 1041, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

cleanup: Cleaning up after exception in <TCP.proxy object at 0x000002353C479348>.
proxy: Could not join cSide thread.
proxy: cSide thread joined.
cleanup: Exception in <TCP.proxy object at 0x000002353C479348>. Printing traceback:
NoneType: None

cleanup: Cleaning up after exception in <TCP.proxy object at 0x000002353C479348>.
proxy: Could not join cSide thread.
proxy: Joining sSide thread...
